### ISSUE TITLE
Dynamically load HAL for updated sensors to increase max range of accelerometer? 

### ISSUE THREAD

**Issue by herbertvuijk** [STMicroelectronics/STMems_Android_Sensor_HAL_Input#2]
Hello,

I'm working on quite an innovative app which uses the accelerometer. It turns out that on several devices the ST Microelektronics accelerometers are limited to a range of 4G, although they support 8G and 16G modes as well according to the specs.

First of all I don't understand why manufaturers of phones are actually limiting / capping the sensor capabilities to 4G? Have seen it a lot on Samsung devices, for example the A40.  On this git repo I see 8G on most of the sensors while the same sensor on my a40 is limited to 4G (LSM6DSL), see attached image
![Screenshot_20200625-131352_Sensor Kinetics](https://user-images.githubusercontent.com/8804409/85709703-cfe6d900-b6e5-11ea-98a0-532492cbfc05.jpg) . While in the .h file I see a limit of 8G (https://github.com/STMicroelectronics/STMems_Android_Sensor_HAL_Input/blob/STMems_Android_Sensor_HAL_Input/conf/conf_LSM6DSL.h) 

Why is it that on some phones the sensor runs in 4G mode instead of 8 or 16? Is it because of old firmware / HAL software?

But more important is that after searching for days on the internet I was hoping maybe you can put me in some direction to work around this issue if it's even possible. Directions I'm currently thinking, but really have no clue if it's nearly possible are:
- Built the STMems Sensor HAL myself and 'replace' the .SO files coming with the phone/ROM. Maybe Android 10, dynamic HAL is an option for that as well. Really don't know if this is possible
- Connect to the hardware directly and write some data to put the sensor into 8 or 16G mode.

I got a feeling that this is probably not possible and I have to live with phones that are capped to 4G. It really is a big issue for the app I'm currently working on.

I'm sorry if this is not really the place for this kind of questions, but I'm quite desperate and hopefully somebody can point me in some direction. 

Regards, Herbert

**Comment by mariotesi** [comment]
Hi Herbert,

Please consider the CDD just report this constrain:
[C-1-4] MUST be capable of measuring from freefall up to four times the gravity(4g) or more on any axis.

So all available  Acc FS >= 4g (4, 8, 16 g) are valid for CTS/VTS purpose. This value is set by the vendor/ODM because they are free to pick the SensorHAL and change this value from the default configuration.

One question: are you sure your phones uses the Input version of SensorHAL ?

Anyway, in order to change the Acc FS in input version of HAL you need to rebuild it (the Input Sensor HAL version is a little bit old anyway still working on Android 10) with your FS and replace it on the phone. This is not so easy as you can imagine because of following considerations:
1) You need the Vendor Android Aosp for your target phone or a similar target configuration for your SoC
2) Please take in account that if your phone has Accelerometer uncalibrated (it's strongly recommended to have in the last 
    Android version)  you also need the accelerometer calibration library (which need a LUA signature) into your SensoHAL path 
    before to re-build it.
3) Since the Sensor HAL also includes other libraries (for example the gyroscope calibration, magnetometer calibration and 
    other libraries for sensor fusion etc etc), you will need also LUA signed for all of that.

Alternatively as you can see in the HAL source code, to change the acc FS you can echo a new value into accel/scale entry into linux system input device filesystem, anyway is not advisable to follow this procedure because some info are loaded by the sensor framework just after android boot, for this reason you may have misalignments between the framework and the linux driver.
